"""Generate a throwaway account for the rain bot to sign as.

The bot needs an account of its own. Not the deployer, whose key funds the
registry, and not the Corvid minter, which gates the collection: a key that
goes into CI is a key that any workflow in a public repository can read, so
it must be one whose loss costs nothing but the TestNet ALGO on it.

**What this writes is a secret.** It goes to `.env.testnet.bot`, which
`.gitignore` already covers via `.env.*`, and only the address is printed.
That is deliberate: an address is public, a mnemonic is not, and a terminal
is a place text gets pasted from. Read the file yourself when you are ready
to put it somewhere.

    poetry run python -m scripts.new_bot_account
    poetry run python -m scripts.new_bot_account --show     # print it too

TestNet only, and the script refuses anything else. A key generated by a
script that also prints it is a key that has been seen by whatever captured
that output; do not carry this one to MainNet, and do not reuse it for
anything that holds value.
"""

import argparse
import logging
import pathlib
import stat

from algosdk import account, mnemonic

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

REPO = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_OUT = REPO / ".env.testnet.bot"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=pathlib.Path,
        default=DEFAULT_OUT,
        help="where to write it (default: %(default)s, which .gitignore covers)",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="print the mnemonic as well as writing it. It will be in your scrollback.",
    )
    parser.add_argument(
        "--force", action="store_true", help="overwrite an existing file"
    )
    args = parser.parse_args(argv)

    if args.out.exists() and not args.force:
        logger.error(
            f"{args.out} already exists. Refusing to overwrite a key that may be "
            "funded or already in a secret store; pass --force if you mean to "
            "replace it, and move the ALGO off the old one first."
        )
        return 1
    if not str(args.out.name).startswith(".env."):
        logger.error(
            f"{args.out.name} is not a .env.* name, so .gitignore does not cover "
            "it and this would write a mnemonic into a tracked path."
        )
        return 1

    private_key, address = account.generate_account()
    phrase = mnemonic.from_private_key(private_key)
    # Round-trip before writing: a file whose mnemonic does not rebuild the
    # address it names is worse than no file, because it fails at signing
    # time on a machine that has nothing else.
    if account.address_from_private_key(mnemonic.to_private_key(phrase)) != address:
        logger.error("The generated mnemonic does not rebuild its own address. Nothing written.")
        return 1

    args.out.write_text(
        "# The rain bot's own account. TestNet throwaway; never MainNet, never\n"
        "# anything holding value. Covered by .gitignore's .env.* rule.\n"
        f"RAIN_MNEMONIC=\"{phrase}\"\n"
    )
    args.out.chmod(stat.S_IRUSR | stat.S_IWUSR)

    logger.info(f"Wrote {args.out} (0600, gitignored).")
    logger.info(f"  address  {address}")
    if args.show:
        logger.info(f"  mnemonic {phrase}")
    else:
        logger.info("  mnemonic written to the file only. Pass --show to print it.")

    logger.info("")
    logger.info("Next, in order:")
    logger.info("  1. Fund it from the TestNet dispenser:")
    logger.info("     https://bank.testnet.algorand.network/")
    logger.info("  2. Take a ticket in an OPEN rain. It cannot enter a gated one:")
    logger.info("     https://corvidlabs.xyz/rain/  (rain 3 'Stake' is open)")
    logger.info("  3. Put it in CI as the repository secret RAIN_MNEMONIC:")
    logger.info("     gh secret set RAIN_MNEMONIC --repo CorvidLabs/arcron-rain < the file")
    logger.info("")
    logger.info(
        "A secret in a public repository is readable by any workflow in it, "
        "including one added by a pull request. That is survivable for this "
        "key and is the reason it is not the deployer's."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
